#!/bin/sh

# Branch atual
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD);

# Commits locais que ainda não subiram
COMMITS=$(git log $CURRENT_BRANCH --not --remotes --pretty=format:%H);

for COMMIT in $COMMITS;do
    MENSAGEM=$(git log --format=%B -n 1 $COMMIT);
    PADRAO="$(echo $MENSAGEM | grep -o -E '#[0-9]*')";
    NUMERO_ISSUE="$(echo $PADRAO | grep -o -E '[0-9]+')";

    CURL_ARGS="-s -S -k";
    API_URL="https://api.github.com/repos/vitorhenriquec/TrabalhoGCM/issues/$NUMERO_ISSUE";
    TOKEN="-H 'Authorization: Token dd9c611dd83cdf7da1a7493b0a622556b4017844'";
    JSON="$(curl $CURL_ARGS $API_URL)";

    NOT_FOUND="$(echo $JSON | jq -r '.message')";

    # Se a mensagem for Not Found, então deu 404
    if [ "$NOT_FOUND" = "Not Found" ];then
        echo "Erro: Issue não encontrada!";
        echo "Push abortado."
        exit 1;
    fi

    # Capturando JSON.state
    STATE="$(echo $JSON | jq -r '.state')";

    if [ "$STATE" = "open" ];then
        echo "Issue aberta. Verificando se possui label 'doing'... [66%]";
    else
        echo "Erro: Issue fechada";
        echo "Push abortado."
        exit 1;
    fi

    # Capturando a quantidade de labels associadas
    LENGTH="$(echo $JSON | jq '.labels | length')";

    NAO_ENCONTROU_DOING = true;

    i=0
    while [ "$i" -lt "$LENGTH" ];do
        PARAMETRO=".labels[$i].name"
        LABEL="$(echo $JSON | jq --compact-output $PARAMETRO)"
        # Verificando se tem label "doing"
        if [ "$LABEL" = "\"doing\"" ];then
            # Achou label "doing"
            echo "Encontrou doing"
            $NAO_ENCONTROU_DOING = false
            break;
        fi
        i=$(( i + 1 ));
    done

    if $NAO_ENCONTROU_DOING;then
        echo "Issue não possui a lable Doing. Push abortado."
        exit 1;
    fi
done
